<?php

namespace OiLab\OiLaravelMetadata\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;
use OiLab\OiLaravelMetadata\Models\JsonLd;
use OiLab\OiLaravelMetadata\OiMetadata;

/**
 * Factory for generating JsonLd model instances.
 *
 * @extends Factory<JsonLd>
 */
class JsonLdFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiMetadata::jsonLdModel();
    }

    /**
     * Define the model's default state.
     *
     * The metable parent must be supplied via the `forMetable()` state, since a
     * JSON-LD object always belongs to a host model.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'graphs' => [
                [
                    '@type' => 'WebPage',
                    'name' => $this->faker->sentence(4),
                    'description' => $this->faker->sentence(12),
                    'url' => $this->faker->url(),
                ],
            ],
        ];
    }

    /**
     * Attach the JSON-LD object to a specific metable model.
     */
    public function forMetable(Model $metable): static
    {
        return $this->state(fn (array $attributes): array => [
            'metable_type' => $metable->getMorphClass(),
            'metable_id' => $metable->getKey(),
        ]);
    }
}
