<?php

namespace OiLab\OiLaravelMetadata\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;
use OiLab\OiLaravelMetadata\Models\Metadata;
use OiLab\OiLaravelMetadata\OiMetadata;

/**
 * Factory for generating Metadata model instances.
 *
 * @extends Factory<Metadata>
 */
class MetadataFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiMetadata::metadataModel();
    }

    /**
     * Define the model's default state.
     *
     * The metable parent must be supplied via the `forMetable()` state, since
     * metadata always belongs to a host model.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'title' => $this->faker->sentence(4),
            'description' => $this->faker->sentence(12),
            'keywords' => $this->faker->words(5),
            'author' => $this->faker->name(),
            'copyright' => '© '.$this->faker->company(),
            'language' => $this->faker->randomElement(['fr', 'en', 'es', 'de']),
            'revisit_after' => '7 days',
            'robots' => 'index, follow',
            'googlebot' => 'index, follow',
        ];
    }

    /**
     * Attach the metadata to a specific metable model.
     */
    public function forMetable(Model $metable): static
    {
        return $this->state(fn (array $attributes): array => [
            'metable_type' => $metable->getMorphClass(),
            'metable_id' => $metable->getKey(),
        ]);
    }
}
