<?php

namespace OiLab\OiLaravelMetadata\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;
use OiLab\OiLaravelMetadata\Models\OpenGraph;
use OiLab\OiLaravelMetadata\OiMetadata;

/**
 * Factory for generating OpenGraph model instances.
 *
 * @extends Factory<OpenGraph>
 */
class OpenGraphFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiMetadata::openGraphModel();
    }

    /**
     * Define the model's default state.
     *
     * The metable parent must be supplied via the `forMetable()` state, since
     * an Open Graph object always belongs to a host model.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'type' => 'website',
            'title' => $this->faker->sentence(4),
            'description' => $this->faker->sentence(12),
            'url' => $this->faker->url(),
            'image' => [
                'url' => $this->faker->imageUrl(1200, 630),
                'width' => 1200,
                'height' => 630,
            ],
        ];
    }

    /**
     * Attach the Open Graph object to a specific metable model.
     */
    public function forMetable(Model $metable): static
    {
        return $this->state(fn (array $attributes): array => [
            'metable_type' => $metable->getMorphClass(),
            'metable_id' => $metable->getKey(),
        ]);
    }
}
